export const ORACLE_CONSTANTS = {
  MAX_ENTROPY_BITS: 2.0,
  ENTROPY_THRESHOLD: 1.5,
  TICK_INTERVAL_MS: 300,
  HEXAGRAM_COUNT: 64,
  ORACLE_RESPONSE_TTL_MS: 60000,
} as const;

export const HEXAGRAM_ACTION_MAP: Record<number, string> = {
  1: 'CREATE',
  2: 'RECEIVE',
  3: 'DIFFICULT_START',
  4: 'MISTAKEN_PATH',
  5: 'PATIENT_WAIT',
  6: 'ADAPT',
  7: 'DISCIPLINE',
  8: 'UNITY',
  9: 'RESTRAIN',
  10: 'TREADING',
  11: 'PEACE',
  12: 'STAGNATION',
  13: 'FELLOWSHIP',
  14: 'POSSESSION',
  15: 'MODESTY',
  16: 'ENTHUSIASM',
  17: 'FOLLOWING',
  18: 'CORRUPTION',
  19: 'APPROACH',
  20: 'CONTEMPLATION',
  21: 'BITING_THROUGH',
  22: 'GRACE',
  23: 'SPLITTING_APART',
  24: 'RETURN',
  25: 'INNOCENCE',
  26: 'POWER_OF_GENTLE',
  27: 'NOURISHMENT',
  28: 'PREPONDERANCE',
  29: 'ABYSSAL',
  30: 'CLINGING',
  31: 'INFLUENCE',
  32: 'DURATION',
  33: 'RETREAT',
  34: 'GREAT_POWER',
  35: 'PROGRESS',
  36: 'YIELD',
  37: 'FAMILY',
  38: 'OPPOSITION',
  39: 'OBSTRUCTION',
  40: 'DELIVERANCE',
  41: 'DECREASE',
  42: 'INCREASE',
  43: 'BREAKTHROUGH',
  44: 'COMING_TO_MEET',
  45: 'GATHERING',
  46: 'PUSHING_UPWARD',
  47: 'OPPRESSION',
  48: 'WELL',
  49: 'REVOLUTION',
  50: 'CALDRON',
  51: 'THUNDER',
  52: 'KEEPING_STILL',
  53: 'DEVELOPMENT',
  54: 'MARRYING_MAIDEN',
  55: 'ABUNDANCE',
  56: 'WANDERING',
  57: 'GENTLE_WIND',
  58: 'JOYOUS_LAKE',
  59: 'DISPERSION',
  60: 'LIMITATION',
  61: 'INNER_TRUTH',
  62: 'PREponderance_SMALL',
  63: 'AFTER_COMPLETION',
  64: 'BEFORE_COMPLETION',
};

export const YAO_STATE_LABELS: Record<number, string> = {
  0: 'OldYin',
  1: 'YoungYang',
  2: 'OldYang',
  3: 'YoungMixed',
};

export const TELEMETRY_SCHEMA = {
  tables: {
    oracle_readings: {
      columns: ['id', 'hexagram_binary', 'entropy', 'timestamp', 'avatar_state'],
    },
    entropy_curves: {
      columns: ['id', 'hexagram_binary', 'entropy', 'tick', 'created_at'],
    },
  },
} as const;
